### ISSUE TITLE
Not compatible with OCaml 4.08

### ISSUE THREAD

**Issue by aantron** [ocsigen/wikidoc#10]
I get this error when pinning wikidoc on 4.08:

```
File "odoc_wiki.ml", line 147, characters 19-38:
147 | module StringSet = Odoc_html.StringSet
                         ^^^^^^^^^^^^^^^^^^^
Error: Unbound module Odoc_html.StringSet
Hint: Did you mean String?
```

It works on 4.07.

**Comment by aantron** [comment]
Incompatibility with 4.08 complicates generating docs for a library with `(let*)`, e.g. Lwt 5.3.0 (see https://travis-ci.org/github/ocsigen/lwt/jobs/678898558#L534).

**Comment by aantron** [comment]
Thanks!
